apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  FOO: "bar"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels: { app: my-app }
  template:
    metadata:
      labels: { app: my-app }
    spec:
      containers:
        - name: nginx
          image: nginx
          envFrom:
            - configMapRef:
                name: my-config
